import type { Metadata } from "next";
import "./globals.css";
// import Header from "@/components/layout/Header";
// import Footer from "@/components/layout/Footer";
import Providers from "@/components/Providers";
import Script from "next/script";
import { Analytics } from '@vercel/analytics/next';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

        <meta name="google-site-verification" content="toPhn3zTF7Y1TKXt1x3B0jw_KDHWXQyn_vWVEIak-eI" />
        <Script defer src="https://cloud.umami.is/script.js" data-website-id="4fc504fc-d39a-455c-944f-fe7412e13fab" />
        {/*
        <Script
          defer src="https://cloud.umami.is/script.js" data-website-id="ef64fec0-87ba-4f08-8be4-06df0d499fe4"
        />
        <Script defer src="https://cloud.umami.is/script.js" data-website-id="1e1fef30-e964-449a-9d2c-4ad7b8e41bd1" />

        <Script
          defer src="https://cloud.umami.is/script.js" data-website-id="267d941e-5055-4446-97c7-aba47ea8f9b7"

        />
        */}

        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-17160239824"
          strategy="afterInteractive"
        />

        {/* Initialize gtag */}
        <Script id="gtag-init" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'AW-17160239824');
        `}
        </Script>

        {/* Fire conversion event */}
        <Script id="gtag-conversion" strategy="afterInteractive">
          {`
          gtag('event', 'conversion', {
            send_to: 'AW-17160239824/ey9iCITJ0tUaEND10fY_'
          });
        `}
        </Script>
      </head>
      <body className={`antialiased`}>
        <Providers>
          {children}
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}
